server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://47.103.15.229:3306/missyou?charactorEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: xjh19951029SHNU!
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true
  redis:
    localhost: 47.103.15.229
    port: 6379
    database: 7
    password:
    listen-pattern: __keyevent@7__:expired

rocketmq:
  consumer:
    consumer-group: SleeveConsumerGroup
  producer:
    producer-group: SleeveProducerGroup
  namesrv-addr: 127.0.0.1:9876

missyou:
  security:
    jwt-key: 8524985xue7594jiany39hui
    token-expired-in: 600000
  order:
    max-sku-limit: 777
    pay-time-limit: 900
    pay-callback-host: http://talelin.com
    pay-callback-path: /v1/payment/wx/notify